### ISSUE TITLE
What if the bandwidth is used up?

### ISSUE THREAD

**Issue by zkpanhao** [PoweredByCloud/resource#12]
Hello, I have used this gadget to deploy my blog's picture, and I see the bandwidth is limited to 10GB, so i want to know what if the bandwidth is used up? Do i need to pay some money or just my picture can't display?

Anyway, Thanks for your good work!

**Comment by beanyoung** [comment]
Currently you don't need to worry about the bandwidth.
I will let you know before pricing plan changes.
