### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by muvich3n** [PoweredByCloud/resource#16]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/75461217/175808233-4962bb84-052d-47f5-bb52-07c201979964.png">

Thank you for the great product. Since there is an error when visiting the site, I am curious to see if this product will continue in the future.
Thanks again Mr.BeanYoung!

**Comment by beanyoung** [comment]
There is a system issue, and I have fixed it.
PoweredBy.Cloud is working now.
Thank you for your feedback!
