### ISSUE TITLE
是不是不能上传video?

### ISSUE THREAD

**Issue by kingwrcy** [PoweredByCloud/resource#4]
传了个MP4文件,16M,在`PowerdByCloud`上看不见,但是在`google drive`里能看到

是通过`PowerdByCloud`上传的.

**Comment by beanyoung** [comment]
PoweredByCloud 并没有任何文件类型的限制。

你能提供一下这个文件在 Google Drive 里的 详情/details 截图吗？

**Comment by kingwrcy** [comment]
吃个饭的功夫回来能显示了,但是打开是黑屏.
我又重传了一个简单的mp4,为什么打开无法播放呢?[链接](https://kingwrcy.stdcdn.com/root/20210302145235.mp4)
我打开是这样的,看进度条是在播放的:
![image](https://user-images.githubusercontent.com/1247324/109610251-7766b600-7b67-11eb-85d5-162cb293bb73.png)

直接打开google drive的链接是可以播放的.


detail如下:
![image](https://user-images.githubusercontent.com/1247324/109610151-530ad980-7b67-11eb-9b56-0915834a83db.png)

**Comment by beanyoung** [comment]
由于浏览器只支持部分编码格式的 mp4，如果你想要用 html5 来播放 mp4 文件的话，需要把文件转成 html5 支持的编码格式。
这个文件你下载下来之后用播放器是能播放的。
Google Drive 应该是做了转码了。

**Comment by kingwrcy** [comment]
ok,感谢！
