### ISSUE TITLE
Button move/copy  files/folders to another site in the Dashboard.

### ISSUE THREAD

**Issue by samuelmarkno** [PoweredByCloud/resource#5]
Hi, the only way to move or copy files to another site is from googledrive, is there the possibility of doing it from the Dashboard Poweredby.cloud?
 
https://cloudup.com/cklScZAZKEV

Greetings.

**Comment by beanyoung** [comment]
Hi,

PoweredBy.Cloud does not support move or copy files, but this feature is on our list.

**Comment by samuelmarkno** [comment]
Thank you for taking the time to respond to my request, great I will wait for that update soon. i will close this issue.
