### ISSUE TITLE
Some Error in video Url? Headers?

### ISSUE THREAD

**Issue by shivampandey0** [PoweredByCloud/resource#6]
I'm working on an app that will play videos over the network in Flutter.

Hosted the videos on google drive with PBC(found it on producthunt)

I'm having this kind of error on iOS only not on Android
[github issue](https://github.com/jhomlala/betterplayer/issues/243)

to check if it's not the video itself or plugin I tried with a random video

[https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4](https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4)

The above video plays without any issue but when I downloaded the same video and uploaded it through PBC and tried to play I got the same error.

Same Video Hosted by PBC : [https://naturefm.stdcdn.com/sample.mp4](https://naturefm.stdcdn.com/sample.mp4)

any solutions for this? 
could you guys get a hint from the above-linked issue? 
Is it something to do with the hosted platform or If I can do something about it?

**Comment by beanyoung** [comment]
Hi,

This issue is Accept-Ranges header in response is missing.
I have fixed this issue but I can't test it on iOS, so if you still can't play this video on iOS, please let me know.

Thank you for your feedback.

**Comment by shivampandey0** [comment]
Awesome, It's working now. 
Thanks
