### ISSUE TITLE
SVG image file upload

### ISSUE THREAD

**Issue by joe-zhan** [PoweredByCloud/resource#9]
Hi, 
when I uploaded the svg file using s3 api to google drive, the content-type of the file retrieved from stdcdn.com is "text/xml" rather than 'image/svg+xml', even I specity the metadata of the file when uploading.
![image](https://user-images.githubusercontent.com/3829984/128498356-bae1ca17-dc57-4144-a6a3-bce67918a4d1.png)

![image](https://user-images.githubusercontent.com/3829984/128498301-70bb77d0-b745-4ce3-bd3c-f013d3066c6d.png)

But it is fine if I uploaded the same file through https://poweredby.cloud web page.

**Comment by beanyoung** [comment]
Hi Zhan,
Thank you for your feedback.
This is a bug in our s3 api implementation, and this bug has been fixed.
Now metadata is working when you use s3 sdk.
Hope you enjoy PoweredBy.Cloud.
